examples/Basics/main.jl

Thanks for the new doc pages btw!

Fix math display in docs

---

src/layers/basic.jl

Closes https://github.com/avik-pal/Lux.jl/issues/130

fix PairwiseFusion docs

---

docs/src/devdocs/layer_implementation.md
examples/SimpleRNN/main.jl
src/layers/recurrent.jl
test/layers/recurrent.jl

context: #135
My first attemt at making recurrent cells more generic. Locally, tests pass. I haven't yet changed docstrings or the LSTM example, I'll gladly do so if the API changes are OK.

Generic recurrent cells

---

src/layers/containers.jl
src/utils.jl
test/layers/containers.jl

Allow indexing into Chains

---

Project.toml
docs/mkdocs.yml
docs/src/api/contrib.md
docs/src/manual/dispatch_custom_inputs.md
src/layers/containers.jl
src/layers/normalize.jl

Allow dispatch using `Lux.apply`

---

Project.toml
docs/src/api/layers.md
docs/src/api/utilities.md
src/Lux.jl
src/autodiff.jl
src/contrib/training.jl
src/layers/basic.jl
src/layers/containers.jl
src/layers/conv.jl
src/layers/display.jl
src/nnlib.jl
src/utils.jl
test/layers/basic.jl
test/layers/containers.jl
test/layers/conv.jl
test/layers/dropout.jl
test/layers/normalize.jl
test/layers/recurrent.jl

Add More Layers

---

lib/LuxLib/Project.toml
lib/LuxLib/src/LuxLib.jl
lib/LuxLib/src/api/batchnorm.jl
lib/LuxLib/src/api/groupnorm.jl
lib/LuxLib/src/deprecated.jl
lib/LuxLib/src/impl/normalization.jl

Fixes the type stability issues in batchnorm

Make normalization typestable

---

Project.toml
docs/src/api/layers.md
src/Lux.jl
src/layers/recurrent.jl
src/utils.jl
test/layers/recurrent.jl

Add sensible recurrent layer wrappers

---

Project.toml
src/autodiff.jl

See discussion https://github.com/SciML/DiffEqFlux.jl/issues/776

remove convert rrule

---

Project.toml
src/contrib/map.jl
test/contrib/map.jl

Fix layer_map for custom layers

---

.github/workflows/CompatHelper.yml
lib/Boltz/Project.toml
lib/Boltz/src/Boltz.jl
lib/Boltz/src/utils.jl
lib/Boltz/src/vision/metalhead.jl
lib/Boltz/src/vision/vgg.jl
lib/Boltz/src/vision/vit.jl
src/transform.jl
test/runtests.jl

Start using Flux2Lux

---

.github/workflows/CI.yml
.github/workflows/CINightly.yml
.github/workflows/Downstream.yml
.github/workflows/Invalidations.yml
Project.toml

Fixes #192 (waiting for https://github.com/JuliaRegistries/General/pull/72444)

Revert github workflows for merged LuxCore.jl

---

README.md

ADAM -> Adam

---

.github/workflows/CompatHelper.yml
Project.toml
docs/src/api/contrib.md
docs/src/devdocs/subpackages.md
src/Lux.jl
src/contrib/share_parameters.jl
test/contrib/share_parameters.jl
test/runtests.jl

Add easy tied weights/parameter sharing support

---

ext/LuxComponentArraysExt.jl
test/ext/LuxComponentArraysExt.jl
test/runtests.jl

Add a patch for #243

---

Project.toml

Remove weakdeps from deps

---

src/layers/recurrent.jl

Fix GRUCell docstring

---

Project.toml
src/layers/recurrent.jl
src/utils.jl

Added '__apply_activation' to 'RNNCell's

---

src/layers/recurrent.jl

Added `AbstractRecurrentCell`

---

Project.toml
src/layers/basic.jl
test/layers/basic.jl

fix https://github.com/LuxDL/Lux.jl/issues/332

Fix errors in applying bilinear layer to ND arrays

---

Project.toml
ext/LuxFluxTransformExt.jl
src/layers/display.jl

We need to tag a release directly on this branch.

Workaround https://github.com/cjdoris/PackageExtensionCompat.jl/issues/9

---

.JuliaFormatter.toml
Project.toml
docs/src/api/contrib.md
examples/ImageNet/data.jl
examples/ImageNet/utils.jl
examples/PolynomialFitting/main.jl
ext/LuxFluxTransformExt.jl
ext/LuxTrackerExt.jl
ext/LuxZygoteExt.jl
src/Lux.jl
src/contrib/training.jl
src/layers/basic.jl
src/layers/containers.jl
src/layers/conv.jl
src/layers/display.jl
src/layers/dropout.jl
src/layers/normalize.jl
src/layers/recurrent.jl
src/utils.jl
test/Project.toml
test/contrib/training.jl
test/ext/LuxFluxTransformExt.jl
test/layers/containers.jl
test/runtests.jl
test/test_utils.jl

Clean up the codebase

---

examples/ImageNet/README.md

Boltz Link was not working, updated

---

test/layers/conv.jl

Add Potential CUDA Grouped Conv segfault test

---

Project.toml
examples/Basics/Project.toml
examples/Basics/main.jl
ext/LuxComponentArraysExt.jl
src/contrib/contrib.jl
src/contrib/freeze.jl
src/contrib/training.jl
src/utils.jl
test/contrib/freeze.jl

* Drop AbstractDifferentiation
* Patch StatefulLayer chainrules for `ps=nothing`
* Patch freezing with ComponentArrays
* Better Docs on trigger package loading

Minor Fixes

---

src/layers/conv.jl

Add perdiodic padding to documentation

---

test/Project.toml
test/aqua.jl
test/misc.jl

Add CA test for Nested AutoDiff

---

docs/src/api/Building_Blocks/WeightInitializers.md
docs/src/manual/weight_initializers.md

Update WeightInitializers documentation

---

docs/tutorials.jl
examples/Basics/Project.toml
examples/BayesianNN/Project.toml
examples/GravitationalWaveForm/Project.toml
examples/HyperNet/Project.toml
examples/NeuralODE/Project.toml
examples/PolynomialFitting/Project.toml
examples/SimpleRNN/Project.toml

…8-00-56-03-521-03339914152
CompatHelper: add new compat entry for Metalhead at version 0.9 for package ImageNet, (keep existing compat)

Docs Again

---

Project.toml
examples/PolynomialFitting/main.jl
examples/SimpleRNN/main.jl
src/layers/recurrent.jl
src/utils.jl
test/layers/conv_tests.jl
test/layers/recurrent_tests.jl

* MultiRNNCell added to docs. Fixes #472 
* RNNCells now accept vector inputs. Fixes #478 
* Catch problems in Conv Transpose early. Fixes #455

General Quality of Life Enhancements

---

Project.toml
docs/src/api/Building_Blocks/LuxCore.md
docs/src/api/Lux/utilities.md
src/Lux.jl
src/utils.jl

Move replicate to LuxCore

---

src/layers/basic.jl

Correct the documentation of the `Dense` constructor

Fix `Dense` documentation

---

Project.toml
examples/BayesianNN/main.jl
ext/LuxReverseDiffExt.jl
ext/LuxTrackerExt.jl
ext/LuxZygoteExt.jl
src/contrib/training.jl
test/contrib/training_tests.jl
test/misc_tests.jl

* Specialize on Functions and add reversediff mode for training
* Fixes https://github.com/LuxDL/Lux.jl/issues/538

QoL improvements for tracing based AD

---

src/transform/simplechains.jl
test/transform/flux_tests.jl
test/transform/simple_chains_tests.jl

Fix SimpleChains for single dims

---

Project.toml
docs/src/manual/nested_autodiff.md
ext/LuxForwardDiffExt.jl
ext/LuxZygoteExt.jl
src/utils.jl
test/helpers/nestedad_tests.jl

Fixes https://github.com/LuxDL/Lux.jl/issues/602

Unstructure structured inputs for reasonable broadcasting

---

bench/helpers.jl
bench/layers.jl

https://github.com/LuxDL/Lux.jl/pull/641 github actions seems to unable to post comment or push, so checking if that is a permissions issue

Add Enzyme to benchmark infra

---

ext/LuxForwardDiffExt/LuxForwardDiffExt.jl
ext/LuxForwardDiffExt/batched_ad.jl
ext/LuxZygoteExt/LuxZygoteExt.jl
ext/LuxZygoteExt/batched_ad.jl
ext/LuxZygoteExt/nested_ad.jl
ext/LuxZygoteExt/training.jl
src/helpers/autodiff.jl
test/helpers/batched_ad_tests.jl

Improvements to Batched Jacobian

---

Project.toml
docs/make.jl
docs/src/introduction/index.md
docs/src/manual/nested_autodiff.md
examples/BayesianNN/main.jl
examples/HyperNet/main.jl
examples/NeuralODE/main.jl
examples/SimpleRNN/main.jl
examples/SymbolicOptimalControl/main.jl
src/Lux.jl
src/chainrules.jl
src/helpers/compact.jl
src/helpers/stateful.jl
test/helpers/batched_ad_tests.jl
test/helpers/compact_tests.jl
test/helpers/nestedad_tests.jl

Patch a compact bug

---

Project.toml
src/contrib/contrib.jl
src/contrib/map.jl

More principled rewrite of layer_map

---

Project.toml
bench/vgg.jl
src/layers/basic.jl

Showed up in https://github.com/LuxDL/Lux.jl/pull/675.

Minor optimizations

---

README.md

Add test guide documentation

---

src/layers/basic.jl

Add `ReverseSequence()` docs

---

docs/src/api/Lux/contrib.md
examples/ConvMixer/main.jl
examples/DDIM/main.jl
examples/HyperNet/main.jl
examples/NeuralODE/main.jl
examples/PolynomialFitting/main.jl
examples/SimpleChains/main.jl
examples/SimpleRNN/main.jl
ext/LuxOptimisersExt.jl
src/contrib/contrib.jl
src/contrib/training.jl
test/contrib/training_tests.jl

First merge https://github.com/LuxDL/Lux.jl/pull/713

Extend training API and update examples

---

Project.toml
src/helpers/stateful.jl
test/helpers/nestedad_tests.jl

fix: nested ad when using direct eval in function

---

docs/src/api/Lux/utilities.md
src/Lux.jl
src/helpers/compact.jl
test/helpers/compact_tests.jl

improvements to compact macro

---

Project.toml
examples/SymbolicOptimalControl/Project.toml
ext/LuxDynamicExpressionsExt.jl
src/layers/extension.jl
test/layers/dynamic_expressions_tests.jl

supercedes #803 #801 
SymbolicRegression doesn't support 0.16+. ~needs https://github.com/MilesCranmer/SymbolicRegression.jl/pull/326~
Last push should handle this

fix: update Dynamic Expressions to 0.19

---

.buildkite/testing.yml
.github/workflows/CI.yml
.github/workflows/CIPreRelease.yml
test/runtests.jl
test/transform/flux_tests.jl

having them be tested together causes dependency resolution issues.

ci: separate testing for groups in buildkite

---

Project.toml
src/layers/containers.jl
test/layers/containers_tests.jl

finally fixes https://github.com/LuxDL/Lux.jl/issues/416

fix: force_inline inside generated functions to avoid recursion issues

---

examples/OptimizationIntegration/main.jl

fix: patch optimization tutorial

---

docs/src/manual/nested_autodiff.md

Just following on the discussion with @avik-pal in #963. 
I am not sure about the formatting of this, I hope there is some CI in place to be sure all looks nice. Happy to make any changes @avik-pal that you think adequate.

Added to Nested AD example how to use `batched_jacobian`

---

examples/SimpleRNN/main.jl

Not sure what this is but it seems counterintuitive (or incomplete).  Feel free to reject or modify.

Remove line about "not saving the model"

---

docs/src/manual/gpu_management.md

In gpu_management.md, fix list fragmentation by putting each code block as part of its list item.

Move code blocks inside bullet list

---

docs/src/manual/interface.md

The docs say they don't expect you to need a refershed on calling models.
But I did.
Implementing a weird custom layer is literally the first thing I have tried to do in Lux.

Link to quickstart explaining calling models in interface

---

docs/src/manual/autodiff.md

not an AD package on own, but probably useful to describe

Add Reactant and TPU to autodiff.md

---

examples/PINN2DPDE/main.jl

For 50,000 training steps, an update every 1000 step is enough detail; 500 step updates clutter the tutorial page

Change update step to thousands in PINN 2D PDE

---

docs/src/manual/compiling_lux_models.md
ext/LuxReactantExt/training.jl
src/Lux.jl

These are directly available upstream

chore: remove debug functionalities of reactant

---

Project.toml
examples/GCN_Cora/Project.toml
examples/GCN_Cora/main.jl

fix: bump reactant min version

---

Project.toml
examples/Qwen3/main.jl
src/layers/attention.jl

feat: faster scaled_dot_product_attention for reactant
