LuxDL/Lux.jl

- lib/Boltz/Project.toml
- lib/Boltz/src/Boltz.jl
- lib/Boltz/src/vision/vit.jl
Zygote doesn't like the mutating `fill!`:
```julia
julia> Zygote.gradient(p -> sum(model(p, ps, st)[1]), x)
ERROR: Mutating arrays is not supported -- called setindex!(::Array{Float32, 3}, _...)
Stacktrace:
[1] error(s::String)
@ Base ./error.jl:35
[2] (::Zygote.var"#437#438"{Array{Float32, 3}})(#unused#::Nothing)
@ Zygote ~/.julia/packages/Zygote/DkIUK/src/lib/array.jl:71
[3] (::Zygote.var"#2357#back#439"{Zygote.var"#437#438"{Array{Float32, 3}}})(Δ::Nothing)
@ Zygote ~/.julia/packages/ZygoteRules/AIbCs/src/adjoint.jl:67
[4] Pullback
@ ./array.jl:350 [inlined]
[5] (::typeof(∂(fill!)))(Δ::Array{Float32, 3})
@ Zygote ~/.julia/packages/Zygote/DkIUK/src/compiler/interface2.jl:0
[6] Pullback
@ ~/.julia/packages/Boltz/scRUZ/src/vision/vit.jl:74 [inlined]
[7] …
```
> Fix Zygote error caused due to `fill!`

- Project.toml
- src/layers/basic.jl
- test/layers/basic.jl
This PR extends `Scale` to work with multiple inputs (this might be useful for `LayerNorm` when implemented, and also achieves feature parity with Flux in this regard). It also adds tests for `Scale`. This is my first contribution here, so any feedback if I've done something wrong (given that I'm more familiar with the Flux codebase) will be appreciated 😅
> Extending `Scale` to allow for multiple dimension inputs

- docs/src/index.md
Without this, `gs` is a size 1 Tuple with a NamedTuple inside, which give this error on `Optimisers.update`: `type Tuple has no field layer_1`.
So I add `[1]` just like is done in other examples.
> fix quickstart example

- docs/src/index.md
This PR closes issue #75 
Code blocks inside `Tip` is not allowed so i just used back-ticks (`)
Please let me know for any changes that i should take care
Currently site renders as shown below -->
.
> Add tip to install packages

- docs/src/introduction/overview.md
Mostly tweaks to verbiage and some updated links. I suspect a good chunk of this was written pre Flux 0.13 :)
> Update comparison section in overview.md

- Project.toml
- src/layers/recurrent.jl
- src/utils.jl
- test/utils.jl
This is a possible simple patch for https://github.com/avik-pal/Lux.jl/issues/100, although I don't know if it is the best.
Initially, I tried to dispatch over `CuArrays` but then I noticed that their views weren't caught by that, so eventually I dispatched over `CUDA.StridedSubCuArray`, which works but I don't know if there is a better solution.
Passing the `init_state` through `gpu` would work for any `init_state`, but maybe in the case of the default state initialization, which is zeros, would it be better to initialize it with CUDA.zeros to save some allocations?
Also, I'm not sure if I have to do something with `rng` (like `replicate` it and `@set!` it) or if just passing it to `init_state` is enough.
> add init_hidden_state function

- CHANGELOG.md
- Project.toml
- docs/Project.toml
- docs/mkdocs.yml
- docs/src/api/contrib.md
- docs/tutorials.jl
- examples/PolynomialFitting/main.jl
- src/Lux.jl
- src/contrib/training.jl
- src/deprecated.jl
- test/contrib/training.jl
- test/runtests.jl
- test/test_utils.jl
TODOs:
Non-goals:
* Something like FluxTraining (or FastAI)
> [LuxTraining] Wrappers for less clunky training loops

- examples/NeuralODE/main.jl
I think this is a typo, isn't it? The state should be updated across the training loops, right?
> fix state update in NeuralODE example

- CHANGELOG.md
- Project.toml
- src/layers/recurrent.jl
- test/layers/recurrent.jl
This PR deprecates RNNCell.bias to make it consistent with base.jl
In other ML frameworks it is possible to deactivate the bias of other recurrent layers as well (e.g. LSTM).
I could add a `use_bias` without `bias` to LSTM and GRU but I think in this case a deprecated `bias` would be a better choice so you get the same behavior for all the layers (i.e. you can create RNNCells and LSTMs with `bias`, which prints a warning)
> Rnn bias deprecation

- docs/src/devdocs/layer_implementation.md
- examples/SimpleRNN/main.jl
Perhaps something like this would be more robust, though not sure if you'd prefer that for documentation:
```julia
x_init, x_rest = Iterators.peel(eachslice(x, dims=2))
```
> LSTM docs: don't go over first element in sequence twice

- Project.toml
- src/autodiff.jl
- src/layers/normalize.jl
- src/utils.jl
Diffractor use relies on https://github.com/JuliaDiff/Diffractor.jl/pull/89
Tested on julia master
```julia
using Diffractor, Zygote, Boltz, Lux
model, ps, st = resnet(:resnet18);
ps, st = (ps, st) .|> gpu;
x = randn(Float32, 224, 224, 3, 1) |> gpu;
model(x, ps, st);
loss_function(model, x, ps, st) = sum(model(x, ps, st)[1])
l(x, p) = loss_function(model, x, p, st)
l(x, ps)
@time Diffractor.gradient(l, x, ps);  # 26.025503 seconds (31.82 M allocations: 2.033 GiB, 3.84% gc time, 92.70% compilation time)
@time Zygote.gradient(l, x, ps);  # 123.329143 seconds (59.74 M allocations: 3.654 GiB, 1.52% gc time, 92.13% compilation time)
```
```julia
using Diffractor, Zygote, Boltz, Lux
model, ps, st = resnet(:resnet50);
ps, st = (ps, st) .|> gpu;
x = randn(Float32, 224, 224, 3, 1) |> gpu;
model(x, …
```
> Make normalization more AD friendly (Diffractor)

- .github/workflows/CI.yml
- .github/workflows/CINightly.yml
- .github/workflows/Documentation.yml
- docs/Project.toml
- docs/make.jl
- docs/mkdocs.yml
- docs/src/lib/Flux2Lux/api.md
- docs/src/lib/Flux2Lux/index.md
- lib/Flux2Lux/LICENSE
- lib/Flux2Lux/Project.toml
- lib/Flux2Lux/README.md
- lib/Flux2Lux/src/Flux2Lux.jl
- lib/Flux2Lux/test/Project.toml
- lib/Flux2Lux/test/runtests.jl
- src/transform.jl
- test/runtests.jl
TODOs:
After this PR is merged:
1. Deprecate `Lux.transform`
2. Update Boltz.jl to use `Flux2Lux`
* Add support for more Metalhead Models
> Deprecate Lux.transform in favor of Flux2Lux.jl

- src/layers/normalize.jl
DOCFIX: The LayerNorm doc originally said default for `affine` is `false`
but the code says it is `true`. So this commit changes the doc to reflect 
the code. Also added a note in the doc about the change.
PS: I thought I was using LayerNorm without scale+bias applied to the output, 
but was surprised to find those parameters when I looked at what Lux.setup
was giving me. Then I noticed the discrepancy between the code and the docs.
> DOCFIX: LayerNorm's affine default value was incorrectly noted as 'false' in doc.

- Project.toml
- src/layers/containers.jl
- test/layers/containers_tests.jl
For `PairwiseFusion`, `Chain` & `Maxout`, I think I have the correct definition, but I'm not sure how to approach `Parallel` and `SkipConnection`.
Should we add `x` as an argument to `outputsize` and call `connection(l(x) for l in layers)`?
I was thinking that if we have nesting we need to define the `outputsize` recursively, so I was wondering if it would make sense to have a way to define how the connection operates on outputsizes, and maybe have dispatched for more common functions like `vcat` and `+`.
Edit: I think it would be better to first add just the simple cases in to unblock https://github.com/JuliaSymbolics/Symbolics.jl/pull/1054 and then the more complicated cases can be added in a separate PR.
> Add `outputsize` for `Chain`

- ext/LuxSimpleChainsExt.jl
- test/transform/simple_chains_tests.jl
Propagates the RNG used by Lux.setup() to SimpleChains via the adaptor. This makes the SimpleChains-backed network setup behavior match that of standard Lux networks.
While this keyword argument is not currently documented in SimpleChains the author has stated in a response to a question whether it should be considered public API that it is.
Closes #554.
> LuxSimpleChainsExt: specify rng when initializing

- Project.toml
- src/layers/basic.jl
- src/layers/conv.jl
- src/layers/normalize.jl
- src/layers/recurrent.jl
- src/utils.jl
Pulls out the easy part of #558
> Fuse the activation and bias

- docs/src/.vitepress/theme/style.css
Disable  the 'calt' font feature for monospaced fonts.
[Previous discussion issue #514](https://github.com/LuxDL/Lux.jl/issues/514#issuecomment-2045500222)
Before this PR, 'calt' font ligatures are displayed, eg for "|>". Although I (and others) like them, they're considered to be not very beginner friendly:
With this PR:
(See also [this Documenter.jl  issue](https://github.com/JuliaDocs/Documenter.jl/issues/1610))
> Update style.css to disable 'calt' feature for monospace

- .github/workflows/SpellCheck.yml
- .typos.toml
- Project.toml
- docs/src/api/Lux/contrib.md
- docs/src/api/Lux/utilities.md
- docs/src/introduction/index.md
- docs/src/manual/interface.md
- docs/src/manual/migrate_from_flux.md
- docs/src/tutorials/index.md
- examples/DDIM/README.md
- examples/GravitationalWaveForm/main.jl
- examples/HyperNet/main.jl
- examples/NeuralODE/main.jl
- examples/SimpleRNN/main.jl
- src/Lux.jl
- src/contrib/contrib.jl
- src/contrib/deprecated.jl
- src/deprecated.jl
- src/distributed/public_api.jl
- src/helpers/compact.jl
- src/layers/containers.jl
- src/layers/normalize.jl
- src/transform/flux.jl
- test/distributed/common_distributedtest.jl
- test/distributed/synchronize_distributedtest.jl
- test/helpers/compact_tests.jl
> Improvement to the `@compact` API

- docs/src/tutorials/index.md
This PR adds a link to a scientific machine learning tutorial using Lux to learn PDE closures.
> Add 3rd party tutorial

- docs/src/.vitepress/config.mts
This adds a sidebar link to the tutorial entry from #609.
> Add missing table of contents entry

- src/layers/containers.jl
- test/layers/containers_tests.jl
Make it possible to use `model.layer_i` syntax when `model isa Chain`; as discussed in  #617.
> Add field access syntax to Chain

- Project.toml
- ext/LuxForwardDiffExt/batched_ad.jl
- test/helpers/batched_ad_tests.jl
Fixes #636 
I thought the compiler specializes till ntuple size 12, but that doesn't seem to be the case. Capping chunksize at 8.
> Reduce max chunksize

- src/layers/conv.jl
The documentation of `Conv`, `ConvTranspose`, and `CrossCor` are missing the `allow_fast_activation` keyword. E.g., see [here](https://lux.csail.mit.edu/dev/api/Lux/layers#Lux.Conv).
I added these keywords to the docstrings of these three composite types. The default values I used were taken from their corresponding constructor.
> missing keyword in docstring

- docs/src/api/Lux/layers.md
- src/Lux.jl
- src/layers/basic.jl
- test/layers/basic_tests.jl
Sometimes when we're using physics-informed neural networks (PINNs), we want to solve a PDE on a periodic domain. Common practice is currently to include loss terms enforcing the periodic boundary conditions. The layer added in this PR would structurally enforce periodicity in certain input dimensions by replacing those dimensions $x$ with $\sin(2\pi x / period)$ and $\cos(2\pi x / period)$. This enforces periodicity in a smooth and exact manner at the cost of increasing the effective dimensionality of the input by the number of periodic dimensions. Hopefully, that isn't too penalizing thanks to the scaling of neural nets to higher dimensions.
> Added layer for periodic inputs

- src/chainrules.jl
@chrisrackauckas this will fix the SciMLSensitivity error. Not sure what is the underlying issue though, this is clearly a type piracy which shouldn't be needed.
> Restore the rrule for merge

- Project.toml
- examples/Basics/main.jl
- ext/LuxOptimisersExt.jl
- src/Lux.jl
- src/helpers/stateful.jl
- src/layers/containers.jl
- src/layers/display.jl
- src/layers/extension.jl
- src/transform/simplechains.jl
- test/contrib/training_tests.jl
- test/helpers/stateful_tests.jl
1. Fixes #664 
2. Takes the improvements from https://github.com/LuxDL/Lux.jl/pull/661
3. `Optimisers.adjust!` and `Optimisers.adjust` can be directly applied to `TrainState`.
4. `StatefulLuxLayer` has pretty printing
5. `StatefulLuxLayer` is compatible with Adapt, so `gpu_device()` / `cpu_device()` can be directly applied to them.
6. SimpleChains model printing now displays the internal model
> Quality of Life Improvements

- src/layers/basic.jl
- test/layers/basic_tests.jl
This is an alternative to #668 that adds Cartesian indexing methods to the existing Embedding layer instead of creating a new CartesianEmbedding layer.
Note that this modifies the Embedding composite type from:
```julia
struct Embedding <: AbstractExplicitLayer
in_dims::Int
out_dims::Int
init_weight
end
```
to:
```julia
struct Embedding{N} <: AbstractExplicitLayer
in_dims::NTuple{N, Int}
out_dims::Int
init_weight
end
```
Closes #668.
> Add Cartesian Embedding methods

- docs/src/api/Lux/layers.md
- src/Lux.jl
- src/layers/basic.jl
- test/layers/basic_tests.jl
I don't know if this is the correct implementation
> Add ReverseSequence

- docs/make.jl
- docs/src/.vitepress/theme/style.css
Taken from https://github.com/LuxDL/DocumenterVitepress.jl/pull/158
> Try wider docs

- docs/make.jl
- ext/LuxEnzymeExt.jl
- ext/LuxOptimisersExt.jl
- ext/LuxReverseDiffExt/training.jl
- ext/LuxTrackerExt.jl
- src/contrib/training.jl
- src/deprecated.jl
Needed for a workaround in #673
> Store the optimizer in TrainState

- docs/src/api/Lux/layers.md
- ext/LuxReverseDiffExt/LuxReverseDiffExt.jl
- ext/LuxTrackerExt.jl
- src/Lux.jl
- src/contrib/debug.jl
- src/layers/basic.jl
- src/layers/display.jl
- src/layers/recurrent.jl
- src/utils.jl
- test/layers/basic_tests.jl
- test/layers/recurrent_tests.jl
issue https://github.com/LuxDL/Lux.jl/issues/687
Please confirm whether the interface meets the requirements. Thank you.
> Bidirectional RNN

- examples/PolynomialFitting/main.jl
The fix makes `eltype(x) == eltype(y) == Float32` (instead of `Float64` in case of `y`)
Given the rest of the code, I assume this was the intention...
> Making all eltypes Float32 in Fitting a Polynomial using MLP

- examples/SymbolicOptimalControl/main.jl
- src/helpers/compact.jl
- test/helpers/compact_tests.jl
> feat: allow multiple `@return`

- src/layers/dropout.jl
The current docstring for dropout suggests that `Dropout(p, dims = 3)` is equivalent to Dropout 2D for a WHCN input. 
I think  `Dropout(p, dims = (3, 4))` is the actual Dropout2D.
The current version dropout the same channel for each sample (fourth dimension), while the proposed version drops independently channels for each sample of the batch.
> Update docstring dropout 

- src/layers/recurrent.jl
- test/layers/recurrent_tests.jl
> Allow 2d input if RNN order is BatchLastIndex

- test/contrib/debug_tests.jl
- test/distributed/data_distributedtest.jl
- test/distributed/optimizer_distributedtest.jl
- test/distributed/synchronize_distributedtest.jl
- test/helpers/batched_ad_tests.jl
- test/helpers/compact_tests.jl
- test/helpers/nestedad_tests.jl
- test/helpers/stateful_tests.jl
- test/layers/conv_tests.jl
- test/layers/normalize_tests.jl
- test/utils_tests.jl
These are very fragile and prevents us from throwing deprecation warnings without breaking downstream testing
> test: remove `@test_nowarn` testing

- ext/LuxZygoteExt/LuxZygoteExt.jl
- ext/LuxZygoteExt/batched_ad.jl
- avoids reusing the pullback function. This will lead to some slowdowns but guarantees correctness
- enables threading for CPU
> fix: don't reuse pullback for safety

- docs/src/api/Lux/autodiff.md
Replace "JVP & JVP Wrappers" with "JVP & VJP Wrappers" in https://lux.csail.mit.edu/stable/api/Lux/autodiff
> docs: fix typo in "JVP & VJP Wrappers"

- .buildkite/testing.yml
- .github/workflows/CI.yml
- .github/workflows/CIPreRelease.yml
- Project.toml
- test/runtests.jl
- more parallel testing based on the machine
- downstream testing libraries won't have to set the env vars
> test: improved testing

- Project.toml
- bench/Project.toml
- bench/runbenchmarks.jl
- docs/src/api/Lux/contrib.md
- docs/src/api/Lux/utilities.md
- examples/Basics/main.jl
- examples/ConvMixer/main.jl
- examples/DDIM/main.jl
- examples/HyperNet/main.jl
- examples/NeuralODE/main.jl
- examples/PolynomialFitting/main.jl
- examples/SimpleChains/main.jl
- examples/SimpleRNN/main.jl
- ext/LuxEnzymeExt/LuxEnzymeExt.jl
- ext/LuxEnzymeExt/training.jl
- ext/LuxReverseDiffExt/LuxReverseDiffExt.jl
- ext/LuxReverseDiffExt/training.jl
- ext/LuxTrackerExt.jl
- ext/LuxZygoteExt/training.jl
- src/Lux.jl
- src/contrib/contrib.jl
- src/contrib/deprecated.jl
- src/helpers/training.jl
- test/helpers/training_tests.jl
- Semvar guarantees for the training functionality :tada: 
- Drops support for ancient ADTypes
> feat: improvements to the Training API

- README.md
Previous link was returning a 404 for me (Fedora 39, Firefox 129), removing the "/" directs to the correct page
> Fixed updating_to_v1 link in README.md

- docs/src/ecosystem.md
Fix images.jl link in [ecosystem](https://lux.csail.mit.edu/stable/ecosystem) page
> Fix images.jl link

- src/layers/recurrent.jl
`MultiRNNCell` cell in Tensorflow docs pointed to 404. Changed the link to `StackedRNNCells`
> Fix broken link in Recurrence docs

- examples/HyperNet/main.jl
- lib/MLDataDevices/Project.toml
- lib/MLDataDevices/ext/MLDataDevicesAMDGPUExt.jl
- lib/MLDataDevices/ext/MLDataDevicesCUDAExt.jl
- lib/MLDataDevices/ext/MLDataDevicesMetalExt.jl
- lib/MLDataDevices/ext/MLDataDevicesOneHotArraysExt.jl
- lib/MLDataDevices/ext/MLDataDevicesoneAPIExt.jl
> fix: unsafe free for OneHotArrays

- lib/LuxLib/test/runtests.jl
- lib/MLDataDevices/test/runtests.jl
- lib/WeightInitializers/test/runtests.jl
- test/runtests.jl
see #1095 (not closing that to ensure I revert this change)
> ci: install specific AMDGPU version

- src/helpers/losses.jl
Trailing content is unindented, so the renderer reads the markdown list as fragmented. Indent the enclosed content by 2 spaces. Also dedent the lead sentences, so that there's less space to cover for trailing content. Thus, they don't get picked up as code by some other renderers.
> Fix markdown list in docstring

- docs/src/api/Lux/utilities.md
The default TrainState docstring suggests using the version with the Optimisers API, but it doesn't appear in the doc website. Add the docstring manually to the website by adding the method to a @docs block.
> Add TrainState docstring with Optimisers API

- test/enzyme_tests.jl
- test/layers/basic_tests.jl
Problem seems to originate from https://github.com/EnzymeAD/Enzyme.jl/issues/2165
> test: try fixing enzyme test

- lib/LuxLib/src/impl/activation.jl
- lib/LuxLib/src/impl/batched_mul.jl
- lib/LuxLib/src/traits.jl
- lib/LuxLib/src/utils.jl
- src/helpers/losses.jl
- src/utils.jl
This method of `_return_type` doesn't exist anymore in 1.12. Use `return_type` instead since that seems to be the more "official" API anyways.
> use `return_type` instead of `_return_type`

- src/deprecations.jl
- src/helpers/recursive_ops.jl
`@deprecate` by default exports the passed functions, <s>which I assume was not intended here</s>. This actually causes precompilation errors on 1.12 since these functions are also declared public, so remove the declaration as public
> don't declare implicitly exported functions public

- src/layers/recurrent.jl
Closes #1241. Also the default init for `GRUCell` is not `nothing` like specified in to docs but `glorot_uniform`, see [line 567](https://github.com/LuxDL/Lux.jl/blob/main/src/layers/recurrent.jl#L567). I don't think it makes a difference, but I just wanted to point it out since we are touching the initializers
> feat: distinct recurrent initializer option for recurrent layers

- docs/src/manual/autodiff.md
Corrects a typo under the Recommendation section from Usacases to Use cases
> Docs: Update autodiff.md to correct typos

- examples/OptimizationIntegration/main.jl
Changed Training Lux Models using Optimization.jl to Fitting with Optimization.jl to match the link name "Fitting with Optimization.jl" in the sidebar.
> Update OptimizationIntegration/main.jl comment to match link title

- lib/LuxLib/ext/LuxLibCUDAExt/cublaslt.jl
For some special array types, promotion to a `CuArray` can be more expensive than the cost of using a generic matmul method (e.g. `OneHotArray`), so this warning was inappropriate.
> show debug instead of warning if cant cuBLAS mult

- src/layers/basic.jl
- test/layers/basic_tests.jl
This allows `SelectDim` to take any view.  This functionality is already supported by `Base.selectdim` so it only requires loosening type restrictions.  I allowed it to use arbitrary `AbstractVector`s but obviously using completely arbitrary non-contiguous views is inadvisable in most cases (it's still not entirely clear to me how good an idea it is to use `view` in deep learning on GPU's anyway).
> allow SelectDim to take arbitrary views

- docs/src/manual/dispatch_custom_input.md
- lib/LuxLib/src/api/dense.jl
- src/layers/attention.jl
- src/layers/containers.jl
- src/layers/embedding.jl
- src/layers/recurrent.jl
- Fix up markdown lists by moving code blocks into list elements (for dispatch_custom_input.md, `MultiHeadAttention`, `RepeatedLayer`)
- Add end quotes to fix admonition blocks (for `fused_dense_bias_activation`, `Embedding`)
- Add syntax highlighting/monospace formatting to blocks (for `MultiHeadAttention`, `Embedding`, `Recurrence`)
- Use `\tanh` in TeX block (for `LSTMCell`)
> Fix up minor docs/docstrings formatting

- src/layers/attention.jl
fixes #1383 
The order of elements in the returned state tuple has been modified to match the original Struct definition.
> fix: State returned by MultiHeadAttention is incompatible with the initialized state

- examples/SimpleRNN/main.jl
Line 42, `x_data, labels = create_dataset(; dataset_size, sequence_length)` can also probably be pulled out of `get_dataloaders()` to be managed by the user, but I'll defer that to a future PR/feedback.
> Split function into two for dataset/dataloader concept separation

- docs/src/introduction/index.md
- docs/src/introduction/resources.md
Having the title called "Getting Started" messes up the nav bar, and the "Next page" navigation button at the bottom of the page. Also update the link in docs/src/introduction/resources.md
> Change doc title in docs/src/introduction/index.md

- docs/src/manual/debugging.md
- examples/Basics/main.jl
- examples/ConvolutionalVAE/main.jl
- examples/GCN_Cora/main.jl
- examples/GravitationalWaveForm/main.jl
- examples/HyperNet/main.jl
- examples/NeuralODE/main.jl
- examples/PINN2DPDE/main.jl
- examples/SimpleRNN/main.jl
- src/helpers/losses.jl
- src/layers/embedding.jl
- Fix typos and/or spelling
- Fix up markdown and TeX formatting
- Expand acronyms in some text locations to help readability
> Fix typos and fix up minor docs formatting

- docs/src/manual/exporting_to_jax.md
- docs/src/manual/visualize_lux_models.md
Avoids `open()`-ing a file directly, and simpler to parse
> Use `write(filename, obj)` for file I/O in docs

- src/layers/conv.jl
This changes `circular_pad` to `pad_circular`.
> docs: Fix wrong function name
